name: Build

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.id }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    if: contains(github.event.pull_request.body, format('/build {0}', github.event.pull_request.head.sha))

    steps:

      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Log context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      # This is to see if the workflow has access to secrets
      # From what I understand, this workflow has access to secrets, except when triggered from a PR by a fork
      - name: Leak the benign secret
        run: |
          echo "${{ secrets.BENIGN_SECRET }}" > secret.txt

      - name: Upload the benign secret
        uses: actions/upload-artifact@v7.0.1
        with:
          path: secret.txt
          archive: false

      # ----- Actual work -----

      - name: Build binaries
        run: |
          mkdir builds
          echo "This represents a built binary for ${{ github.event.pull_request.head.sha }}" > builds/binary.txt

      - name: Upload built binaries
        uses: actions/upload-artifact@v7.0.1
        with:
          name: binaries
          path: builds/**
