name: Build Commit

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

jobs:
  build:
    name: Build Commit
    runs-on: ubuntu-24.04

    steps:

      - name: Log context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      # This is to see if the workflow has access to secrets
      # From what I understand, this workflow always has access to secrets
      - name: Leak the benign secret
        run: |
          mkdir secrets
          echo "${{ secrets.BENIGN_SECRET }}" > secrets/secret.txt

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: secrets
          path: secrets
          archive: false
