name: Check

on:
  workflow_dispatch:
  push:

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04

    steps:

      - name: Randomly fail
        shell: pwsh
        run: |
          $roll = Get-Random -Minimum 0 -Maximum 100
          $failProbability = 50
          Write-Host "Rolled $roll"
          Write-Host "Fail probability $failProbability"
          
          if ($roll -lt $failProbability) {
             throw "Failed"
          }
          
          Write-Host "Success"
