name: PR Merge Gatekeeper

on:
  pull_request:

jobs:
  check:
    name: PR Merge Gatekeeper
    runs-on: ubuntu-24.04

    steps:

      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Check statuses
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # See https://cli.github.com/manual/gh_pr_checks
          $statusesJson = gh pr checks ${{ github.event.pull_request.number }} --json bucket,name
          $statuses = $statusesJson | ConvertFrom-Json
          
          $ignoredStatuses = @(
              "PR Merge Gatekeeper" # Should always ignore self
          )
          
          # Must be in the status list
          # This means these cannot be skipped
          $requiredStatuses = @()
          
          # Must pass or skip if present
          foreach ($status in $statuses) {
              if ($status.name -in $ignoredStatuses) {
                  continue
              }
          
              if (!($status.bucket -in @("pass", "skipping"))) {
                  Write-Host "Status check has not passed or has not been skipped.`nName: $($status.name)`nCurrent status: $($status.bucket)"
                  exit 1
              }
          }
          
          # Ensure required are present
          $presentStatuses = $statuses.name
          foreach ($requiredStatus in $requiredStatuses) {
              if (!($requiredStatus -in $presentStatuses)) {
                  Write-Host "Required status check is not present.`nName: $($requiredStatus)"
                  exit 1
              }
          }
