name: PR Status Check

on:
  workflow_run:
    workflows:
      - Check
    types:
      - completed
  status:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.event.workflow_run.head_sha || github.event.commit.sha }}"
  cancel-in-progress: true

jobs:
  check:
    name: PR Status Check
    runs-on: ubuntu-24.04
    permissions:
      statuses: write

    if: github.event.context != github.workflow

    steps:

      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      - name: Check statuses
        run: | 
          .github/pr-status-check.pwsh `
              "${{ github.repository }}" `
              "${{ github.event.workflow_run.head_sha || github.event.commit.sha }}" `
              "${{ github.workflow }}" `
              true `
              "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          GH_TOKEN: ${{ github.token }}
